import "../globals.scss";
import NavbarWrapper from "@/components/navbar/navbarWrapper";
import FooterWrapper from "@/components/footer/footerWrapper";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { locales, Locale } from "@/lib/i18n";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "BJJ Insight",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

export default function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { locale: Locale };
}) {
  return (
    <html lang={params.locale}>
      <body className="layout">
        <NavbarWrapper />
        <main className="content">{children}</main>
        <FooterWrapper />
      </body>
    </html>
  );
}
